name: Generate Bookmarks

on:
  push:

jobs:
  generate-bookmarks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install
        npm install -g uglify-js
        sudo apt-get install jq

    - name: Generate bookmarklets
      run: |
        mkdir -p output
        ./create_bookmarklet.sh -o ./output ./*.js

    - name: Generate importable HTML
      run: node ./export_bookmarks -f "Audible List Tools" -o ./output/bookmarks.html ./output/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bookmarks
        path: output/bookmarks.html

  create-release:
    needs: generate-bookmarks
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: bookmarks
        path: output

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        body: |
          ## 🔖 New Release

          This release includes the latest version of the Audible List Tools bookmarklets.
          
          ### 📦 Assets
          - `bookmarks.html` - Import this file into your browser's bookmarks

          ---
          ## 🔄 Automated Release Notes
        append_body: true
        files: ./output/bookmarks.html
